 Loads a JSON file generated by l3map.py and creates a simple HTML report.
import json
import sys
from pathlib import Path

def load_l3map(file_path):
    try:
        with open(file_path, 'r') as f:
            return json.load(f)
    except Exception as e:
        print(f"Error loading {file_path}: {e}")
        sys.exit(1)

def generate_html(data, output_file):
    html = [
        "<html><head><title>L3 Interface and ARP Map</title>",
        "<style>",
        "table { border-collapse: collapse; width: 100%; }",
        "th, td { border: 1px solid #ccc; padding: 6px; font-family: monospace; }",
        "th { background-color: #f2f2f2; }",
        "</style></head><body>",
        "<h2>Layer 3 Interfaces</h2><table>",
        "<tr><th>Interface</th><th>IP Address</th><th>Status</th><th>Description</th></tr>"
    ]

    for iface in data.get("interfaces", []):
        html.append(f"<tr><td>{iface.get('name')}</td>"
                    f"<td>{iface.get('ip')}</td>"
                    f"<td>{iface.get('status')}</td>"
                    f"<td>{iface.get('description', '')}</td></tr>")
    
    html.append("</table><h2>ARP Table</h2><table>")
    html.append("<tr><th>IP Address</th><th>MAC Address</th><th>Interface</th></tr>")
    
    for entry in data.get("arp_table", []):
        html.append(f"<tr><td>{entry.get('ip')}</td>"
                    f"<td>{entry.get('mac')}</td>"
                    f"<td>{entry.get('interface')}</td></tr>")

    html.append("</table></body></html>")

    try:
        with open(output_file, 'w') as f:
            f.write("\n".join(html))
        print(f"HTML report generated: {output_file}")
    except Exception as e:
        print(f"Error writing to {output_file}: {e}")

def main():
    if len(sys.argv) != 3:
        print("Usage: python l3mapviz.py <l3map.json> <output.html>")
        sys.exit(1)

    l3map_file = sys.argv[1]
    output_html = sys.argv[2]

    if not Path(l3map_file).exists():
        print(f"File not found: {l3map_file}")
        sys.exit(1)

    data = load_l3map(l3map_file)
    generate_html(data, output_html)

if __name__ == "__main__":
    main()
